#!/bin/bash

# https://github.com/abonillasuse/cf-intro

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

QUANT=$2
c=1

case "$1" in
  "list") echo "   Available Users"
    cf orgs
    cf org-users selab
    ;;
  "show") echo "   Showing spaces"
    cf spaces
    ;;
  "useradd")  echo "     Creating user "$2" in selab org and dev/prod space"
    cf create-user $2 --origin ldap
    cf set-org-role $2 selab OrgManager
    cf set-space-role $2 selab prod SpaceDeveloper
    cf set-space-role $2 selab prod SpaceManager
    cf set-space-role $2 selab dev SpaceDeveloper
    cf set-space-role $2 selab dev SpaceManager
    ;;
  "create")  echo "     Creating "$2" users in "$org" and target "$target
    while [ $c -le $QUANT ]; do
    cf create-space space$c -o susecon
    cf create-user student$c susecon
    #cf set-org-role student$i susecon OrgManager
    cf set-space-role student$c susecon space$c SpaceDeveloper
    ((c++))
    done;;
  "remove") echo "    Removing "$QUANT" accounts"
    sleep 3
    while [ $c -le $QUANT ]; do
    cf delete-user student$c
    cf delete-space space$c -o susecon
    ((c++))
    done;;
  "help") echo "     Usage: cfglcfg list/useradd/show/create/remove/help [username/quantity]"
    echo "  cfglcfg list                        List Orgs and Users in selab"
    echo "  cfglcfg useradd username            Add a User from LDAP"
    echo "  cfglcfg show                        List all Spaces"
    echo "  cfglcfg create 15                   Create 15 student Users"
    echo "  cfglcfg remove 15                   Remove 15 student Users"
    ;;
  "") echo "Use 'managecfgl help' for assistance";;
esac
